cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    
    
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:product_id>/', views.cart_add, name='cart_add'),
 path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
 
 
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    
    
    path("admin/", admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
    
    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'


urlpatterns = [
    
 path('', views.product_list, name='product_list'),
 path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
 path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
 
]

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'recommended_products': recommended_products})

shop/templates/shop/base/base.html
{% load static %}

<!DOCTYPE html>
<html>

 <head>
    
 <meta charset="utf-8" />
 <title>{% block title %}My shop{% endblock %}</title>

 
 <!-- Css and Js files -->
 {% include 'shop/base/scripts.html' %}
  <!-- Css and Js files -->


 <!-- header files -->
 {% include 'shop/base/header.html' %}
 <!-- header files -->
 
 </head>


 <body>
 <div id="header">

 </div>
 <div id="subheader">
 
 </div>


 <div id="content">
 {% block content %}
 
 {% endblock %}
 </div>

<!-- footer -->
{% include 'shop/base/footer.html' %}
<!-- footer -->


{% comment %} <!-- js files -->
{% include 'shop/js.html' %}
<!-- js files --> {% endcomment %}


 </body>
</html

shop/templates/shop/base/footer.html
 <!-- SERVICES-->
 <section class="py-5 bg-light">
  <div class="container">
    <div class="row text-center gy-3">
      <div class="col-lg-4">
        <div class="d-inline-block">
          <div class="d-flex align-items-end">
            <svg class="svg-icon svg-icon-big svg-icon-light">
              <use xlink:href="#delivery-time-1"> </use>
            </svg>
            <div class="text-start ms-3">
              <h6 class="text-uppercase mb-1">Free shipping</h6>
              <p class="text-sm mb-0 text-muted">Free shipping worldwide</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="d-inline-block">
          <div class="d-flex align-items-end">
            <svg class="svg-icon svg-icon-big svg-icon-light">
              <use xlink:href="#helpline-24h-1"> </use>
            </svg>
            <div class="text-start ms-3">
              <h6 class="text-uppercase mb-1">24 x 7 service</h6>
              <p class="text-sm mb-0 text-muted">Free shipping worldwide</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="d-inline-block">
          <div class="d-flex align-items-end">
            <svg class="svg-icon svg-icon-big svg-icon-light">
              <use xlink:href="#label-tag-1"> </use>
            </svg>
            <div class="text-start ms-3">
              <h6 class="text-uppercase mb-1">Festivaloffers</h6>
              <p class="text-sm mb-0 text-muted">Free shipping worldwide</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<footer class="bg-dark text-white">
    <div class="container py-4">
      </div>
      <div class="border-top pt-4" style="border-color: #1d1d1d !important">
        <div class="row">
          <div class="col-md-6 text-center text-md-start">
            <p class="small text-muted mb-0">&copy; 2023 All rights reserved.</p>
          </div>
          <div class="col-md-6 text-center text-md-end">
            <p class="small text-muted mb-0">Made by <a class="text-white reset-anchor" href=#>Alexio Junior Aaron </a></p>
           
          </div>
        </div>
      </div>
    </div>
  </footer>
  

shop/templates/shop/base/header.html
<div class="page-holder bg-light">
    <!-- navbar-->
    <header class="header bg-white">
      <div class="container px-lg-3">
        <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'shop:product_list' %}"><span class="fw-bold text-uppercase text-dark">Boutique</span></a>
          <button class="navbar-toggler navbar-toggler-end" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <!-- Link--><a class="nav-link" href="{% url 'shop:product_list' %}">Home</a>
              </li>
              <li class="nav-item">
                <!-- Link--><a class="nav-link" href="{% url 'shop:product_list' %}">Shop</a>
              </li>
              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                <div class="dropdown-menu mt-3 shadow-sm" aria-labelledby="pagesDropdown"><a class="dropdown-item border-0 transition-link" href=#>Clothes</a><a class="dropdown-item border-0 transition-link" href=#>Shoes</a><a class="dropdown-item border-0 transition-link" href=#>Watches</a><a class="dropdown-item border-0 transition-link" href=#>Electronics</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto">               
              <li class="nav-item"><a class="nav-link" href="{% url 'cart:cart_detail' %}"> <i class="fas fa-dolly-flatbed me-1 text-gray"></i>Cart<small class="text-gray fw-normal"></small></a></li>
            </ul>
            
          </div>
          <div class="cart">
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
            Your cart:
            <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
            </a>
            {% elif not order %}
            Your cart is empty.
            {% endif %}
            {% endwith %}
         </div>
        </nav>

      </div>
    </header>

shop/templates/shop/base/scripts.html
{% load static %}
 
 
  <!-- gLightbox gallery-->
  <link rel="stylesheet" href= "{%static "vendor/glightbox/css/glightbox.min.css" %}">
  <!-- Range slider-->
  <link rel="stylesheet" href="{%static "vendor/nouislider/nouislider.min.css" %}">
  <!-- Choices CSS-->
  <link rel="stylesheet" href="{%static "vendor/choices.js/public/assets/styles/choices.min.css" %}">
  <!-- Swiper slider-->
  <link rel="stylesheet" href="{%static "vendor/swiper/swiper-bundle.min.css" %}">
  <!-- Google fonts-->
  <link rel="stylesheet" href="{%static "https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap" %}">
  <link rel="stylesheet" href="{%static "https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap" %}">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{%static "css/style.default.css" %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{%static "css/custom.css" %}">
  <!-- Favicon-->
  <link rel="shortcut icon" href="{%static "img/favicon.png" %}">
<!-- formcss-->
  <link href="{% static "css/form.css" %}" rel="stylesheet">

  <!-- pdfcss-->
  <link href="{% static "css/pdf.css" %}" rel="stylesheet">


 <!-- JavaScript files-->
 <script src="{%static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
 <script src="{%static "vendor/glightbox/js/glightbox.min.js" %}"></script>
 <script src="{%static "vendor/nouislider/nouislider.min.js" %}"></script>
 <script src="{%static "vendor/swiper/swiper-bundle.min.js" %}"></script>
 <script src="{%static "vendor/choices.js/public/assets/scripts/choices.min.js" %}"></script>
 <script src="{%static "js/front.js" %}"></script>